# APPUNTI PYTHON: LIBRERIA NUMPY

NumPy è una libreria di Python fondamentale per il calcolo scientifico e l'analisi dei dati. Offre una vasta gamma di funzioni e strumenti, inclusi array multidimensionali (più efficienti delle liste Python), funzioni matematiche, statistiche e operazioni di algebra lineare. Di seguito si riportano alcuni concetti chiave.


## ARRAY

### CREAZIONE DI ARRAY tramite funzioni NUMPY

Puoi creare array di NumPy con __np.array(shape, dtype=float)__ o utilizzando altre funzioni come:
1) np.zeros() che crea un array con tutti zeri
2) np.ones() che crea un array con tutti 1
3) np.arange([start,] stop, [step,] dtype=None) dove di defaul si inizia da zero e si va avant con step di 1
4) np.linspace(start, stop, num=, endpoint=True, retstep=False, dtype=None) genera un array di numeri equamente distanziati su un intervallo specificato
   - endpoint: se True, include il valore di stop come ultimo elemento; se False, lo esclude. Di default è True
   - retstep: se True, restituisce sia l'array che il passo tra i valori. Di default è False
   - dtype: il tipo di dato degli elementi dell'array
5) np.random.rand(d0, d1, ..., dn) crea un array con dimensioni d0,...,dn e elementi con distribuzione uniforme tra 0 e 1

 A volte quando bisogna creare un array dnetro dei cicli for è utile creare una lista vuota, che si riempie man mano all'interno di un ciclo for utilizzando una funzione __lista_vuota.append(i)__ dove "i" è l'elemento da inserire all'interno della lista,  per poi convertirla in array, un esempio è il seguente:

In [16]:
import numpy as np

# 1. Crea una lista vuota
lista_vuota = []

# 2. Usa un ciclo for per riempire la lista
for i in range(10):  # Ad esempio, riempiamo la lista con i numeri da 0 a 9
    lista_vuota.append(i)

# 3. Converti la lista in un array NumPy
array = np.array(lista_vuota)

# 4. Stampa l'array
print(array)


[0 1 2 3 4 5 6 7 8 9]


### COME FUNZIONA LA SHAPE

### DIMENSIONI degli ARRAY

Gli arrayin python possono avere diverse dimensioni. Di seguito un esempio di array uni e bi dimensionale.

In [17]:
import numpy as np
a = np.array([1, 2, 3])  # Array 1D
b = np.array([[1, 2, 3], [4, 5, 6]])  # Array 2D
print('un esempio di array unidimensionale:', a)
print('un esempio di array bidimensionale:', b)

un esempio di array unidimensionale: [1 2 3]
un esempio di array bidimensionale: [[1 2 3]
 [4 5 6]]


L'array unidimensionale non è nè un array riga nè un array colonna però può essere interpretato in modi diversi:
* Array riga: a.reshape(1, 3) oppure a[np.newaxis, :] — risultato: [[1, 2, 3]]
* Array colonna: a.reshape(3, 1) oppure a[:, np.newaxis] — risultato: [[1], [2], [3]]
Si può anche fare il trasposto di un array usando questa funzione:

In [18]:
b_trasposta=b.T #b è una matrice con 2 righe e 3 colonne mentre b_trasposta è una matrice con 3 righe e due colonne
print(b_trasposta)

[[1 4]
 [2 5]
 [3 6]]


Si nota quindi come le parentesi quadre indichino le righe, ognuna di queste parentesi quadre deve avere lo stesso numero di elementi (che corrisponde al numero di colonne della matrice), il numero di parentesi quadre inoltre identifica il numero di righe della matrice.

### INDICIZZAZIONE E SLICING (array di array)

### OPERAZIONE SUGLI ARRAY

Puoi effettuare operazioni come addizione, sottrazione, moltiplicazione e divisione direttamente sugli array.

In [21]:
a = np.array([1, 2, 3])  # Array 1D
b = np.array([4, 5, 6])
print(a+b, a-b, a*b, a/b)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [23]:
a_2=a+10 #aggiunge 10 ad ogni elemnto dell'array
print(a_2)

[11 12 13]


## FUNZIONI UNIVERSALI

## STATISTICA

### CREAZIONE DI UN ISTOGRAMMA

### PLOTTARE LA GAUSSIANA SOPRA L'ISTOGRAMMA